# Generated by Django 4.0.1 on 2022-01-23 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primertabla',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
