# Generated by Django 4.0.1 on 2022-01-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_alter_primertabla_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primertabla',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
