# Generated by Django 4.0.1 on 2022-02-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0003_alter_imagetable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/'),
        ),
    ]
